exports.config = {
  conventions: {
    assets: /^app\/assets\//
  },
  modules: {
    definition: false,
    wrapper: false
  },
  npm: {
      enabled: false,
  },
  paths: {
    "public": 'public'
  },
  files: {
    javascripts: {
      joinTo: {
        'js/main.js': 'app/js/main.js',
        'js/perfmatters.js': 'app/js/perfmatters.js'
        // 'js/index.js': /^app\/js\/index\//,
        // 'js/pizza.js': /^app\/js\/pizza\//
      }
    },
    stylesheets: {
      joinTo: {
        // 'css/app.css': 'app/css/pizza/*.css'
        'css/print.css': 'app/css/site/print.css',
        'css/style.css': 'app/css/site/style.css',
        'css/bootstrap.css': 'app/css/bootstrap/*.css',
        'css/pizza.css': 'app/css/pizza/*.css'
      }
    }
  }
};

// ---
// generated by coffee-script 1.9.2
